name: Pushed job (bad)
on: push
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout
        with:
          fetch-depth: 1
      - uses: Alorel/npm-check-updates@f8096aa9edc7aa3a39e9c91f220da471ce9338e1
        name: Check update
